analyzer:
  errors:
    avoid_dynamic_calls: ignore
    library_private_types_in_public_api: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    non_constant_identifier_names: false
