name: transporter
description: A transporter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  animated_size_and_fade: ^4.0.0
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  country_picker: ^2.0.26

  analyzer: '>=4.6.0 <=5.12.0'
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pinput: ^1.2.2

  intl_utils: ^2.8.7
  flutter_toggle_tab: ^1.4.1
  google_maps_flutter: ^2.9.0
  intersperse: ^2.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  path_provider: ^2.0.12

flutter_intl:
  enabled: true
  class_name: Strings

dependency_overrides:
  analyzer: '>=6.0.0 <7.0.0' # Adjust if necessary

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.0.1
  json_serializable: ^6.5.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    # Images and Icons
    - assets/images/
    - assets/icons/
    - assets/images/profile/
    - assets/images/onboarding/
    - assets/images/authentication/
    - assets/icons/authentication/
    - assets/icons/bottom_navigation/
    - assets/icons/home/
    - assets/icons/drawer/
    - assets/icons/complain/

    # JSON Data
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
