name: transporter

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
env:
  DEFINE_GOOGLE_MAPS_API_KEY: ${{ secrets.DEFINE_GOOGLE_MAPS_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'

      - name: Install Dependencies
        run: flutter packages get

      - name: Analyze
        run: flutter analyze lib test integration_test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Build release apK
        run: flutter build apk --flavor production -t lib/main_production.dart --dart-define=DEFINE_GOOGLE_MAPS_API_KEY=$DEFINE_GOOGLE_MAPS_API_KEY

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: Sign Apk
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/apk/production/release/
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/production/release/app-production-release-unsigned-signed.apk

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/production/release/app-production-release-unsigned-signed.apk'
          token: ${{ secrets.TOKEN }}
          tag: v1.0.${{ github.run_number }}
